"""empty message

Revision ID: 342e9678879f
Revises: 
Create Date: 2026-01-31 19:26:57.912009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342e9678879f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
